# Generated by Django 5.1.5 on 2025-03-24 09:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0002_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='uid',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
