# Generated by Django 5.1.5 on 2025-03-25 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0003_remove_customuser_uid_alter_customuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_detail', models.TextField()),
                ('comment_date', models.DateField(auto_now_add=True)),
                ('blog_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commnettitle', to='blogger.blog')),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
